name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install lcov gcovr cmake g++ libgtest-dev
        
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make test

      - name: Generate coverage report
        run: |
          cd build
          make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./build/coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
         with:
          files: build/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}


